# Herdr theme fragment generated by Omarchy.
# This file is rendered into the current theme as herdr.toml.
# ~/.config/omarchy/hooks/theme-set.d/sync-herdr merges it into ~/.config/herdr/config.toml.

[theme]
name = "terminal"

[theme.custom]
# Keep Herdr pane surfaces transparent so the terminal background still comes from Omarchy.
panel_bg = "reset"

# Core Herdr palette tokens.
background = "{{ bg }}"
foreground = "{{ fg }}"
accent = "{{ accent }}"
muted = "{{ muted }}"
black = "{{ color0 }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
magenta = "{{ magenta }}"
cyan = "{{ cyan }}"
white = "{{ bright_fg }}"
