#!/bin/bash
# Generate ~/.config/hypr/envs.conf from a 1Password item.
#
# Source: a 1P item titled "tailor-envs" (in $TAILOR_OP_ACCOUNT) with text
# fields where label = env var name and value = env var value.
#
# Adding/editing an env: edit the 1Password item directly. No local files.

set -euo pipefail

TAILOR_OP_ACCOUNT="${TAILOR_OP_ACCOUNT:-chamberofsecrets.1password.com}"
ITEM="tailor-envs"
TARGET="$HOME/.config/hypr/envs.conf"

mkdir -p "$(dirname "$TARGET")"

if ! item_json=$(op item get "$ITEM" --account "$TAILOR_OP_ACCOUNT" --format json 2>/dev/null); then
  echo "  ✗ 1Password item '$ITEM' not found in $TAILOR_OP_ACCOUNT"
  echo "    Create a Secure Note titled '$ITEM' with text fields where:"
  echo "      label = env var name (e.g. WEBUI)"
  echo "      value = env var value (e.g. https://your-url/)"
  exit 1
fi

{
  echo "# Hyprland environment variables"
  echo "# Generated by tailor from 1Password item '$ITEM' in $TAILOR_OP_ACCOUNT"
  echo "# Do not edit by hand — edit the 1Password item instead"
  echo ""
  echo "$item_json" | jq -r '
    .fields[]
    | select(.value != null and .value != "" and .label != "notesPlain")
    | "env = \(.label),\(.value)"
  '
} > "$TARGET"

count=$(grep -c '^env = ' "$TARGET" || true)
echo "  ✓ Wrote $TARGET ($count env vars)"
